### ISSUE TITLE
Cimsy as a blog

### ISSUE THREAD

**Issue by tyeeman** [honestcode/cimsy#1]
Thanks for writing cimsy, nice and fast. Is it possible to make a blog out of cimsy? I'm looking for a markdown blog with either categories or tags (one or the other). I don't want to use wordpress.

**Comment by honestcode** [comment]
It's possible, I suppose, but complex because the system isn't designed around a database. Blogs with categories and tags more-or-less require a central taxonomy repository to keep all the links together. 

You might consider [MDWiki](http://dynalon.github.io/mdwiki/#!index.md), which might be a more robust solution for you.
